### ISSUE TITLE
끄투코리아의 모든 리소스 삭제조치 부탁드립니다.

### ISSUE THREAD

**Issue by Kim-Daewoon** [korharu/KKuTu#1]
안녕하세요. 끄투코리아 총 관리자 김대운 입니다.
끄투코리아 레포지토리에 아래와 같이 명시되어 있습니다.

`끄투코리아 에 추가된 모든 리소스(이미지,음성 등)의 저작권은 끄투코리아에 있으며, 다른 서버에서의 사용을 허용하지 않습니다.`

빠른 시일내에 끄투코리아의 모든 리소스를 삭제해주시면 감사하겠습니다.

**Comment by korharu** [comment]
아 죄송합니다 readme 맨 위쪽을 안봤네요... ㅠㅠ 지우겠습니다 ㅠ
